# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Lecteur' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  modules_path = '../node_modules'
  rn_path = "#{modules_path}/react-native"
  rn_maps_path = "#{modules_path}/react-native-maps"
  pod 'TesseractOCRiOS', :git => 'git://github.com/parallaxe/Tesseract-OCR-iOS.git', :branch => 'macos-support'
  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

#   ld: warning: directory not found for option '-L/Users/jonathan/Library/Developer/Xcode/DerivedData/Lecteur-drujvzvystziukckfetzstfxdqhg/Build/Products/Release-iphoneos/RNTextDetector'
# ld: warning: directory not found for option '-L/Users/jonathan/Library/Developer/Xcode/DerivedData/Lecteur-drujvzvystziukckfetzstfxdqhg/Build/Products/Release-iphoneos/TesseractOCRiOS'
# ld: warning: directory not found for option '-L/Users/jonathan/Library/Developer/Xcode/DerivedData/Lecteur-drujvzvystziukckfetzstfxdqhg/Build/Products/Release-iphoneos/TextToSpeech'
# ld: warning: directory not found for option '-L/Users/jonathan/Library/Developer/Xcode/DerivedData/Lecteur-drujvzvystziukckfetzstfxdqhg/Build/Products/Release-iphoneos/react-native-camera'

  pod 'react-native-camera', path: "#{modules_path}/react-native-camera"
  pod 'RNTextDetector', path: "#{modules_path}/react-native-text-detector/ios"
  pod 'TextToSpeech', path: "#{modules_path}/react-native-tts/TextToSpeech.podspec"
  
  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  # Pods for Lecteur

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'TesseractOCRiOS' 
          target.build_configurations.each do |config|
              config.build_settings['ENABLE_BITCODE'] = 'NO'
          end
          header_phase = target.build_phases().select do |phase|
              phase.is_a? Xcodeproj::Project::PBXHeadersBuildPhase
          end.first
  
          duplicated_header_files = header_phase.files.select do |file|
              file.display_name == 'config_auto.h'
          end
  
          duplicated_header_files.each do |file|
              header_phase.remove_build_file file
          end
      end
    end
  end
end

